-- Conky, a system monitor https://github.com/brndnmtthws/conky
--
-- This configuration file is Lua code. You can write code in here, and it will
-- execute when Conky loads. You can use it to generate your own advanced
-- configurations.
--
-- Try this (remove the `--`):
--
--   print("Loading Conky config")
--
-- For more on Lua, see:
-- https://www.lua.org/pil/contents.html
--
-- Conky Lua API: https://conky.cc/lua

-- Configuration settings: https://conky.cc/config_settings
conky.config = {
    alignment = 'top_right',
    background = true,
    border_width = 20,
    cpu_avg_samples = 2,
    default_color = 'white',
    default_outline_color = 'white',
    default_shade_color = 'white',
    double_buffer = true,
    draw_borders = false,
    draw_graph_borders = true,
    draw_outline = false,
    draw_shades = false,
    extra_newline = false,
    font = 'Inconsolata:bold:size=13',
    gap_x = 33,
    gap_y = 33,
    minimum_height = 1102,
    minimum_width = 390,
    net_avg_samples = 2,
    no_buffers = true,
    out_to_console = false,
    out_to_ncurses = false,
    out_to_stderr = false,
    out_to_wayland = false,
    out_to_x = true,
    own_window = true,
    own_window_class = 'Conky',
    -- own_window_type = 'override',
    own_window_hints = 'undecorated,sticky,below,skip_taskbar,skip_pager',
    own_window_colour = '#ef181818',
    own_window_argb_visual = true,
    show_graph_range = true,
    show_graph_scale = true,
    stippled_borders = 0,
    update_interval = 1.0,
    uppercase = false,
    use_spacer = 'none',
    use_xft = true,
    times_in_seconds = true,
}

-- Variables: https://conky.cc/variables
conky.text = [[
${voffset 50}$alignc${font Red Hat Display:bold:size=75}${time %R}$font
${voffset 65}$alignc${offset -2}$nodename ${color grey}up: $color${format_time $uptime "\hh \mm"}\
${if_match "${battery_status}" == "charged"}\
	${color cyan}${battery_percent}%${color}\
${endif}\
${color grey} battery:$color ${if_match "${battery_status}" == "charging"}\
${color cyan}${battery_percent}% ${format_time $battery_time "\hh \mm"}${color}${endif}\
${if_match "${battery_status}" == "discharging"}\
${if_match ${battery_percent} >= 50}\
${color green}${battery_percent}% ${format_time $battery_time "\hh \mm"}${color}${endif}\
${if_match ${battery_percent} < 50}\
${color yellow}${battery_percent}% ${format_time $battery_time "\hh \mm"}${color}${endif}\
${if_match ${battery_percent} < 35}\
${color orange}${battery_percent}% ${format_time $battery_time "\hh \mm"}${color}${endif}\
${if_match ${battery_percent} < 20}\
${color red}${battery_percent}% ${format_time $battery_time "\hh \mm"}${color}${endif}${endif}

${color grey}RAM:$color $mem/$memmax $alignr$memperc% ${voffset 1}${membar 8,100}
${color grey}CPU:$color ${freq_g}GHz $alignr$cpu% ${voffset 1}${cpubar 8,100}
${if_match "${exec cat ~/.config/conky/current/current.txt}" != ""}\
${exec ~/.config/conky/scripts/cover.sh}${image ~/.config/conky/current/current.jpg -p 1,378 -s 389x389 -n}
${font Red Hat Display:bold:size=17}${scroll wait 34 ${exec ~/.config/conky/scripts/title.sh}}$font
${color grey}${font Red Hat Display:bold:size=13}${scroll wait 47 ${exec ~/.config/conky/scripts/artist.sh}}$font$color
${voffset 407}${exec ~/.config/conky/scripts/time.sh}$alignr${exec ~/.config/conky/scripts/length.sh}$font
${voffset -18}${offset 46}${execbar 6,295 ~/.config/conky/scripts/position.sh}
$alignc${font Red Hat Display:bold:size=12}${scroll wait 47 ${color grey}${exec ~/.config/conky/scripts/album.sh}}$color$endif

${color grey}audio clients:$color
${exec ~/.config/conky/scripts/sources.sh}
]]
